name = "a0b_stm32f401_tim11_timer_selftest"
description = "A0B STM32F401 TIM11 Timer sefltest"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files = ["a0b_stm32f401_tim11_timer_selftest.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[configuration.values]
a0b_armv7m.fpu_extension = "VFPv4"

[[depends-on]]
a0b_stm32f401_tim11_timer = "*"
a0b_timer = "*"

[[pins]]
a0b_stm32f401_tim11_timer = { path='..' }
